In [1]:
pip install transformers


[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 MB 6.3 MB/s eta 0:00:0000:0100:01
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [1]:
#pretrained model get downloaded
from transformers import pipeline
classifier=pipeline('sentiment-analysis') #for sentiment analysis

/Users/sharafunneesapp/anaconda3/lib/python3.11/site-packages/transformers/utils/generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [2]:
classifier("i am so happy")

[{'label': 'POSITIVE', 'score': 0.9998812675476074}]

In [3]:
classifier("the food is not tasty")

[{'label': 'NEGATIVE', 'score': 0.9997794032096863}]

In [5]:
classifier("the cloths in shop are unique and beautiful but staffs are rude")

[{'label': 'NEGATIVE', 'score': 0.994140088558197}]

In [8]:
result=classifier(["the course is tough to learn.","But it will be good carrier transition."])
for check in result:
    print(f"label:{check['label']},with score:{round(check['score'],4)}")

label:NEGATIVE,with score:0.9997
label:POSITIVE,with score:0.9958


In [9]:
classifier=pipeline('sentiment-analysis',model='nlptown/bert-base-multilingual-uncased-sentiment') #translation

In [11]:
classifier("i love you") #can deal french, english,spanish,italian etc

[{'label': '5 stars', 'score': 0.8546809554100037}]

In [15]:
pip install --upgrade transformers tensorflow torch


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 6.8 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 402.6/402.6 kB 7.5 MB/s eta 0:00:00ta 0:00:01


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.6/177.6 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.3/410.3 kB 2.0 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 7.2 MB/s eta 0:00:00a 0:00:01m
  Attempting uninstall: safetensors
    Found existing installation: safetensors 0.3.2
    Uninstalling safetensors-0.3.2:
      Successfully uninstalled safetensors-0.3.2
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2023.4.0
    Uninstalling fsspec-2023.4.0:
      Successfully uninstalled fsspec-2023.4.0
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.15.1
    Uninstalling huggingface-hub-0.15.1:
      Successfully uninstalled huggingface-hub-0.15.1
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.13.2
    Uninstalling tokenizers-0.13.2:
      Successfully uninstalled tokenizers-0.13.2
  Attempting uninstall: transformers
    Found ex

In [18]:
from transformers import pipeline, AutoModelForSequenceClassification, AutoTokenizer

model_name = 'nlptown/bert-base-multilingual-uncased-sentiment'
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)
classifier = pipeline('sentiment-analysis', model=model, tokenizer=tokenizer)



In [20]:
# Test the classifier
print(classifier("I love this!"))

#level/star 5 having high accuracy

[{'label': '5 stars', 'score': 0.9236248135566711}]


In [22]:
model_name='distilbert-base-uncased-finetuned-sst-2-english'
tokenizer=AutoTokenizer.from_pretrained(model_name)

In [23]:
result=tokenizer("i am so excited to learn transformer")#converted into tokens

In [24]:
print(result)

{'input_ids': [101, 1045, 2572, 2061, 7568, 2000, 4553, 10938, 2121, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [26]:
result=tokenizer(["i am happy to learn pytorch library","it is bit confusing"],padding=True,truncation=True,max_length=512,return_tensors="tf")


In [27]:
print(result) #indexes will be similar to all the sentences

{'input_ids': <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[  101,  1045,  2572,  3407,  2000,  4553,  1052, 22123,  2953,
         2818,  3075,   102],
       [  101,  2009,  2003,  2978, 16801,   102,     0,     0,     0,
            0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]], dtype=int32)>}
